import json
import subprocess
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


@dataclass
class PRInfo:
    branch_name: str = ""
    title: str = ""
    body: str = ""
    files_changed: list[str] = field(default_factory=list)
    metrics_before: dict = field(default_factory=dict)
    metrics_after: dict = field(default_factory=dict)
    created: bool = False
    pr_url: str = ""


class PRBuilder:
    def __init__(self, config=None):
        self.config = config
        self.branch_prefix = getattr(config, 'pr_branch_prefix', 'evolution/') if config else 'evolution/'
        self.git_user = getattr(config, 'git_user', 'cogu-evolution') if config else 'cogu-evolution'
        self.git_email = getattr(config, 'git_email', 'evolution@cogu.local') if config else 'evolution@cogu.local'

    def create_evolution_pr(
        self,
        target: str,
        baseline_content: str,
        evolved_content: str,
        metrics_before: dict,
        metrics_after: dict,
        repo_dir: str = "",
    ) -> PRInfo:
        timestamp = int(time.time())
        branch_name = f"{self.branch_prefix}{target}-{timestamp}"
        pr = PRInfo(
            branch_name=branch_name,
            title=f"[Evolution] Improve {target}",
            metrics_before=metrics_before,
            metrics_after=metrics_after,
        )

        pr.body = self._build_pr_body(target, metrics_before, metrics_after)

        if not repo_dir:
            return pr

        repo_path = Path(repo_dir)
        try:
            self._run_git(repo_path, ["checkout", "-b", branch_name])
            self._write_evolved_file(repo_path, target, evolved_content)
            self._run_git(repo_path, ["add", "."])
            self._run_git(repo_path, ["commit", "-m", pr.title, "--author", f"{self.git_user} <{self.git_email}>"])
            pr.created = True
            pr.files_changed = [target]
        except Exception:
            try:
                self._run_git(repo_path, ["checkout", "-"])
                self._run_git(repo_path, ["branch", "-D", branch_name])
            except Exception:
                pass

        return pr

    def _build_pr_body(self, target: str, before: dict, after: dict) -> str:
        lines = [
            "## Evolution Results",
            "",
            f"**Target:** `{target}`",
            "",
            "### Metrics Comparison",
            "",
            "| Metric | Before | After | Delta |",
            "|--------|--------|-------|-------|",
        ]
        all_keys = set(list(before.keys()) + list(after.keys()))
        for key in sorted(all_keys):
            b = before.get(key, "N/A")
            a = after.get(key, "N/A")
            if isinstance(b, float) and isinstance(a, float):
                delta = a - b
                sign = "+" if delta >= 0 else ""
                lines.append(f"| {key} | {b:.3f} | {a:.3f} | {sign}{delta:.3f} |")
            else:
                lines.append(f"| {key} | {b} | {a} | — |")

        lines.extend([
            "",
            "### Auto-generated by COGU Evolution System",
            f"*Generated at {time.strftime('%Y-%m-%d %H:%M:%S')}*",
        ])
        return "\n".join(lines)

    def _write_evolved_file(self, repo_path: Path, target: str, content: str):
        target_path = repo_path / target
        target_path.parent.mkdir(parents=True, exist_ok=True)
        target_path.write_text(content, encoding="utf-8")

    def _run_git(self, cwd: Path, args: list[str]):
        cmd = ["git"] + args
        subprocess.run(cmd, cwd=str(cwd), capture_output=True, timeout=30)

    def list_evolution_branches(self, repo_dir: str = ".") -> list[str]:
        try:
            result = subprocess.run(
                ["git", "branch", "--list", f"{self.branch_prefix}*"],
                cwd=repo_dir, capture_output=True, text=True, timeout=10,
            )
            return [b.strip().lstrip('* ') for b in result.stdout.strip().split('\n') if b.strip()]
        except Exception:
            return []

    def cleanup_branches(self, repo_dir: str = ".", keep_last: int = 5):
        branches = self.list_evolution_branches(repo_dir)
        if len(branches) <= keep_last:
            return
        to_delete = sorted(branches)[:-keep_last]
        for branch in to_delete:
            try:
                subprocess.run(
                    ["git", "branch", "-D", branch],
                    cwd=repo_dir, capture_output=True, timeout=10,
                )
            except Exception:
                pass
